spring.datasource.url: jdbc:mysql://rialexlx.beget.tech/rialexlx_blog?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
spring.datasource.username: rialexlx_blog
spring.datasource.password: Test01
spring:flyway:locations=classpath:db-migration:
spring.jpa.hibernate.ddl-auto: none
server:port: 3606
someParameter: 4337

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +79850080211
blog.email: rialex@rambler.ru
blog.copyright: Alexander Riabchinsky
blog.copyrightFrom: 2022

#spring.mail.host: smtp.gmail.com
#spring.mail.port: 587
#spring.mail.username: testdbbox@gmail.com
#spring.mail.password: parolesimple
#spring.mail.properties.mail.smtp.auth: true
#spring.mail.properties.mail.smtp.starttls.enable: true

spring.mail.protocol: smtps
spring.mail.host: smtp.mail.ru
spring.mail.port: 465
spring.mail.username:  testbd@internet.ru
spring.mail.password: hvYDUwgKj6fkDkFCkgSN
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.ssl.enable: true