INSERT INTO posts(is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) VALUES(1, 'ACCEPTED',6,1, '2022-07-09-12-01-01','Бэкенд и Фронтенд','Как сделать собственный сайт',3);
INSERT INTO posts(is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) VALUES(1, 'ACCEPTED',6,2, '2022-07-09-12-01-02','Многопоточность','Как запустить одновременно 1000 потоков',4);
INSERT INTO posts(is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) VALUES(1, 'ACCEPTED',6,3, '2022-07-09-12-01-03','Логирование','Употребление info и debug',6);
INSERT INTO posts(is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) VALUES(1, 'ACCEPTED',6,4, '2022-07-09-12-01-04','ООП','Важнейшую роль в языке Java анимает понятие Объекта',6);
INSERT INTO posts(is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) VALUES(1, 'ACCEPTED',6,5, '2022-07-09-12-01-05','Оформление сайтов','Большие возможности для создания красивых сайтов предоставляет язык CSS',7);
INSERT INTO posts(is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) VALUES(1, 'ACCEPTED',6,6, '2022-07-09-12-01-06','История Java','Язык Java существует уже несколько десятилетий и является одним из самых популярных',8);
INSERT INTO tag2post(post_id, tag_id) VALUES(1,1);
INSERT INTO tag2post(post_id, tag_id) VALUES(2,1);
INSERT INTO tag2post(post_id, tag_id) VALUES(3,1);
INSERT INTO tag2post(post_id, tag_id) VALUES(4,1);
INSERT INTO tag2post(post_id, tag_id) VALUES(5,1);
INSERT INTO tag2post(post_id, tag_id) VALUES(6,1);
INSERT INTO tag2post(post_id, tag_id) VALUES(7,1);
INSERT INTO tag2post(post_id, tag_id) VALUES(2,4);
INSERT INTO tag2post(post_id, tag_id) VALUES(3,4);
INSERT INTO tag2post(post_id, tag_id) VALUES(4,4);
INSERT INTO tag2post(post_id, tag_id) VALUES(5,4);
INSERT INTO tag2post(post_id, tag_id) VALUES(6,4);
INSERT INTO tag2post(post_id, tag_id) VALUES(3,2);
INSERT INTO tag2post(post_id, tag_id) VALUES(7,2);
INSERT INTO tag2post(post_id, tag_id) VALUES(8,2);
INSERT INTO tag2post(post_id, tag_id) VALUES(3,3);
INSERT INTO tag2post(post_id, tag_id) VALUES(7,3);
